server.port=8080
spring.application.name=ems-backend


spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jjroqvlocsblnacryipz
spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=5

app.jwt.secret=${EMS_JWT_SECRET:change-this-development-secret-change-this-development-secret}
app.jwt.expiration-ms=86400000
